### ISSUE TITLE
Add Searching Algorithms

### ISSUE THREAD

**Issue by hydraveer** [hydraveer/Standard_algorithms#4]
Add all searching algorithms, It will help beginner for better understanding of data structure and algorithms.

**Comment by parag477** [comment]
Hey I want to work on this. Please assign me.

**Comment by VishnuAmit** [comment]
Hey @hydraveer. Id like to work on this issue if its still available for me. Kindly assign it to me and will deliver this by today !

**Comment by AdityaDhavale** [comment]
@hydraveer I would like to work on this isssue , please assign me
